apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - image: ghcr.io/startupnationlabs/react-flight-tracker-satellite/api
          name: api
          ports:
            - containerPort: 5566
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 10002
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu: "2"
            limits:
              memory: "2Gi"
              cpu: "8"
          env:
            - name: CELESTRACK_URL
              value: https://celestrak.org/NORAD/elements/
            - name: SPACETRACK_URL
              value: https://www.space-track.org
            - name: HOST
              value: "0.0.0.0"
            - name: SPACETRACK_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: spacetrack-crendentials
            - name: SPACETRACK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: spacetrack-crendentials
          livenessProbe:
            httpGet:
              path: /livez
              port: 10002
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 10002
            initialDelaySeconds: 5
            periodSeconds: 20
      restartPolicy: Always
