apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 9f57c070021c5ebf6e543539b0ded3604f5d3dbb


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
