apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 23e1d88b8a8ba4b1a788f302b25a95c5c3b55f95


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
