apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 128075d3738bc53647beba9c1e2ffd0c60a1794d
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/nginx-cache
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/nginx-cache
    newTag: 128075d3738bc53647beba9c1e2ffd0c60a1794d


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml