apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 7427acdecd50d086122fb79b24cca0c742386d6e


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
