apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 8683d897d9a8b21dfdfac870ef49baf59de970e0
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/nginx-cache
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/nginx-cache
    newTag: 8683d897d9a8b21dfdfac870ef49baf59de970e0


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml