apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../base

images:
  - name: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newName: ghcr.io/startupnationlabs/realtime-satellite-api/api
    newTag: 77c1c8e65e604d46bcd25acc7d22192be20709ae


patches:
  - target:
      kind: Ingress
      name: api-ingress
    path: ingress-patch.yaml
